name: univlm
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - accelerate==1.8.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - attrdict==2.0.1
      - attrs==25.3.0
      - av==15.0.0
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.46.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - deepspeed==0.17.2
      - diffusers==0.32.2
      - dill==0.3.8
      - einops==0.6.1
      - einops-exts==0.0.4
      - fastapi==0.116.1
      - ffmpy==0.6.0
      - filelock==3.13.1
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.33.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jaxtyping==0.3.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - latex2mathml==3.78.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - narwhals==1.47.0
      - networkx==3.3
      - ninja==1.11.1.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.16.0
      - pillow==10.4.0
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - rpds-py==0.26.0
      - ruff==0.12.3
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.47.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - timm==0.9.16
      - tokenizers==0.21.2
      - tomlkit==0.12.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdiffeq==0.2.5
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.2.0
      - typer==0.16.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - wadler-lindig==0.1.7
      - wandb==0.21.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - websockets==11.0.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
